spawn-world: "world"

spawn-location:
  world: "world"
  x: 0.5
  y: 100.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

branding:
  server-name: "amirwopi_fox"
  author: "amirwopi"
  github: "https://github.com/amirwopi"
  console-banner:
    - "&6========================================"
    - "&eFlameLobby &7| &fby &bamirwopi"
    - "&7GitHub: &fhttps://github.com/amirwopi"
    - "&6========================================"

messages:
  prefix: "Â§e[amirwopi_fox]Â§r "

  errors:
    server-selector-unavailable: "Â§cServer selector is not available!"
    music-unavailable: "Â§cMusic system is not available!"

  parkour:
    disabled: "Â§cParkour is disabled."
    ajparkour-missing: "Â§cajParkour is not installed."

  lobby:
    fallen-teleport: "Â§7Teleported you to Lobby, stay safe :)"

  server-connect-failed: "Â§cFailed to connect to server: {server}"

  music:
    no-tracks: "Â§cNo music tracks available!"
    permanently-disabled: "Â§cMusic has been permanently disabled!"
    enabled: "Â§aMusic has been enabled!"

music-gui:
  title: "Music Player"
  page-format: "- Page {page}/{pages}"

server-selector:
  title: "Game Selector"
  social:
    telegram:
      name: "âœˆ Telegram"
      url: "https://github.com/amirwopi"
      chat-label: "Telegram Â» "
    discord:
      name: "ğŸ’¬ Discord"
      url: "https://github.com/amirwopi"
      chat-label: "Discord Â» "
    teamspeak:
      name: "ğŸ§ TeamSpeak"
      url: "github.com/amirwopi"
      chat-label: "TeamSpeak Â» "
    website:
      name: "ğŸŒ Website"
      url: "https://github.com/amirwopi"
      chat-label: "Website Â» "

lobby-items:
  enabled: true
  slots:
    server-selector: 0
    parkour-start: 1
    pvp-sword: 4
    music-player: 6
    elytra: 7
    fireworks: 8
  items:
    parkour-start:
      material: LIME_DYE
      name: "Â§aParkour Â§7(Click)"
      lore:
        - "Â§7Click to start parkour"
    elytra:
      name: "Â§bElytra"
      lore:
        - "Â§7For lobby flying"
    fireworks:
      amount: 1
      name: "Â§eFireworks"
      lore:
        - "Â§7Boost your elytra"

ajparkour:
  enabled: true
  start-command: "/ajp start"
  stop-command: "/ajp leave"

jump-pad:
  enabled: true
  trigger: LIGHT_WEIGHTED_PRESSURE_PLATE
  horizontal: 8.5
  vertical: 1.6

auto-announcer:
  enabled: true
  interval-seconds: 60
  messages:
    - "Â§eWelcome to Â§6amirwopi_foxÂ§e!"
    - "Â§bUse the compass to open the game selector."

protections:
  spawn:
    prevent-block-break: true
    prevent-block-place: true
    prevent-bucket-empty: true
    prevent-bucket-fill: true
    prevent-item-drop: true
    prevent-swap-hand: true
    prevent-inventory-move: true
